### PR TITLE
DOCKER-130 upgrade to alpine 3.17

### PR DESCRIPTION
**Pull request by pierre-guillot-gh**
.

### CODE REVIEW

**Comment by pierre-guillot-gh** [comment]
Hey @carminevassallo I could not test locally, as I can't build the image on an arm64 CPU. Any tips on how to validate this?

**Comment by carminevassallo** [comment]
> Hey @carminevassallo I could not test locally, as I can't build the image on an arm64 CPU. Any tips on how to validate this?

Hey @pierre-guillot-gh, it should still work fine on arm64. Could you please try building the `4/Dockerfile` using the latest scanner version publicly available (I found `4.7.0.2747`)? Please try something like:

`docker build --no-cache --build-arg SONAR_SCANNER_VERSION=4.7.0.2747 -t sonar-scanner-cli:4.7.0 .`

Let me know if it works, we should anyways release a new scanner-cli version as the latest available is dated February 22.

**Comment by pierre-guillot-gh** [comment]
Does not work on my side:
```
➜  4 git:(master) docker build --no-cache --build-arg SONAR_SCANNER_VERSION=4.7.0.2747 -t sonar-scanner-cli:4.7.0 .
[+] Building 7.6s (8/10)                                                                                                                                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                                                                                                                        0.0s
 => => transferring dockerfile: 2.16kB                                                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/alpine:3.15                                                                                                                                                                              2.8s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                                                               0.0s
 => [1/5] FROM docker.io/library/alpine:3.15@sha256:cf34c62ee8eb3fe8aa24c1fab45d7e9d12768d945c3f5a6fd6a63d901e898479                                                                                                                        0.9s
 => => resolve docker.io/library/alpine:3.15@sha256:cf34c62ee8eb3fe8aa24c1fab45d7e9d12768d945c3f5a6fd6a63d901e898479                                                                                                                        0.0s
 => => sha256:cf34c62ee8eb3fe8aa24c1fab45d7e9d12768d945c3f5a6fd6a63d901e898479 1.64kB / 1.64kB                                                                                                                                              0.0s
 => => sha256:3ce94ef1fbafb0750209b432c59d72fd1ec8db0ae665e65714e36b2ecbef0a97 528B / 528B                                                                                                                                                  0.0s
 => => sha256:8aa73fd46299044b14829b57d37938a9a7ae6223bc20945508f75d67002332ff 1.49kB / 1.49kB                                                                                                                                              0.0s
 => => sha256:47517142f6ba87eca6b7bdca1e0df160b74671c81e4b9605dad38c1862a43be3 2.72MB / 2.72MB                                                                                                                                              0.7s
 => => extracting sha256:47517142f6ba87eca6b7bdca1e0df160b74671c81e4b9605dad38c1862a43be3                                                                                                                                                   0.1s
 => [internal] load build context                                                                                                                                                                                                           0.0s
 => => transferring context: 1.22kB                                                                                                                                                                                                         0.0s
 => [2/5] WORKDIR /opt                                                                                                                                                                                                                      0.0s
 => ERROR [3/5] RUN set -eux;     addgroup -S -g 1000 scanner-cli;     adduser -S -D -u 1000 -G scanner-cli scanner-cli;     apk add --no-cache --virtual build-dependencies wget unzip gnupg;     apk add --no-cache git python3 py-pip b  3.9s
------
 > [3/5] RUN set -eux;     addgroup -S -g 1000 scanner-cli;     adduser -S -D -u 1000 -G scanner-cli scanner-cli;     apk add --no-cache --virtual build-dependencies wget unzip gnupg;     apk add --no-cache git python3 py-pip bash shellcheck 'nodejs>12' openjdk11-jre curl musl-locales musl-locales-lang;     wget -U "scannercli" -q -O /opt/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747.zip;     wget -U "scannercli" -q -O /opt/sonar-scanner-cli.zip.asc https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747.zip.asc;     for server in $(shuf -e hkps://keys.openpgp.org                             hkps://keyserver.ubuntu.com) ; do         gpg --batch --keyserver "${server}" --recv-keys 679F1EE92B19609DE816FDE81DB198F93525EC1A && break || : ;     done;     gpg --verify /opt/sonar-scanner-cli.zip.asc /opt/sonar-scanner-cli.zip;     unzip sonar-scanner-cli.zip;     rm sonar-scanner-cli.zip sonar-scanner-cli.zip.asc;     mv sonar-scanner-4.7.0.2747 /opt/sonar-scanner;     pip install --no-cache-dir --upgrade pip;     pip install --no-cache-dir pylint;     apk del --purge build-dependencies;     mkdir -p "/usr/src" "/opt/sonar-scanner/.sonar" "/opt/sonar-scanner/.sonar/cache";     chown -R scanner-cli:scanner-cli "/opt/sonar-scanner" "/usr/src";     chmod -R 777 "/usr/src" "/opt/sonar-scanner/.sonar";:
#7 0.132 + addgroup -S -g 1000 scanner-cli
#7 0.135 + adduser -S -D -u 1000 -G scanner-cli scanner-cli
#7 0.140 + apk add --no-cache --virtual build-dependencies wget unzip gnupg
#7 0.144 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
#7 0.469 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
#7 0.698 (1/35) Installing libunistring (0.9.10-r1)
#7 0.773 (2/35) Installing libidn2 (2.3.2-r0)
#7 0.826 (3/35) Installing wget (1.21.2-r2)
#7 0.880 (4/35) Installing unzip (6.0-r9)
#7 0.942 (5/35) Installing libgpg-error (1.42-r1)
#7 0.983 (6/35) Installing libassuan (2.5.5-r0)
#7 1.018 (7/35) Installing libcap (2.61-r0)
#7 1.064 (8/35) Installing ncurses-terminfo-base (6.3_p20211120-r1)
#7 1.104 (9/35) Installing ncurses-libs (6.3_p20211120-r1)
#7 1.173 (10/35) Installing pinentry (1.2.0-r0)
#7 1.456 Executing pinentry-1.2.0-r0.post-install
#7 1.463 (11/35) Installing libgcrypt (1.9.4-r0)
#7 1.643 (12/35) Installing gnupg-gpgconf (2.2.31-r2)
#7 1.701 (13/35) Installing libbz2 (1.0.8-r1)
#7 1.744 (14/35) Installing sqlite-libs (3.36.0-r0)
#7 1.816 (15/35) Installing gpg (2.2.31-r2)
#7 2.059 (16/35) Installing npth (1.6-r1)
#7 2.097 (17/35) Installing gpg-agent (2.2.31-r2)
#7 2.179 (18/35) Installing gpg-wks-server (2.2.31-r2)
#7 2.218 (19/35) Installing libksba (1.6.0-r0)
#7 2.271 (20/35) Installing gpgsm (2.2.31-r2)
#7 2.359 (21/35) Installing gpgv (2.2.31-r2)
#7 2.415 (22/35) Installing gmp (6.2.1-r1)
#7 2.469 (23/35) Installing nettle (3.7.3-r0)
#7 2.546 (24/35) Installing libffi (3.4.2-r1)
#7 2.597 (25/35) Installing p11-kit (0.24.0-r1)
#7 2.695 (26/35) Installing libtasn1 (4.18.0-r1)
#7 2.781 (27/35) Installing gnutls (3.7.1-r1)
#7 2.943 (28/35) Installing gdbm (1.22-r0)
#7 2.978 (29/35) Installing libsasl (2.1.28-r0)
#7 3.027 (30/35) Installing libldap (2.6.2-r0)
#7 3.101 (31/35) Installing gnupg-dirmngr (2.2.31-r2)
#7 3.192 (32/35) Installing gnupg-utils (2.2.31-r2)
#7 3.253 (33/35) Installing gnupg-wks-client (2.2.31-r2)
#7 3.293 (34/35) Installing gnupg (2.2.31-r2)
#7 3.326 (35/35) Installing build-dependencies (20221220.141323)
#7 3.327 Executing busybox-1.34.1-r7.trigger
#7 3.336 OK: 20 MiB in 49 packages
#7 3.363 + apk add --no-cache git python3 py-pip bash shellcheck 'nodejs>12' openjdk11-jre curl musl-locales musl-locales-lang
#7 3.367 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
#7 3.644 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
#7 3.839 ERROR: unable to select packages:
#7 3.853   shellcheck (no such package):
#7 3.853     required by: world[shellcheck]
------
executor failed running [/bin/sh -c set -eux;     addgroup -S -g ${GID} scanner-cli;     adduser -S -D -u ${UID} -G scanner-cli scanner-cli;     apk add --no-cache --virtual build-dependencies wget unzip gnupg;     apk add --no-cache git python3 py-pip bash shellcheck 'nodejs>12' openjdk11-jre curl musl-locales musl-locales-lang;     wget -U "scannercli" -q -O /opt/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip;     wget -U "scannercli" -q -O /opt/sonar-scanner-cli.zip.asc https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip.asc;     for server in $(shuf -e hkps://keys.openpgp.org                             hkps://keyserver.ubuntu.com) ; do         gpg --batch --keyserver "${server}" --recv-keys 679F1EE92B19609DE816FDE81DB198F93525EC1A && break || : ;     done;     gpg --verify /opt/sonar-scanner-cli.zip.asc /opt/sonar-scanner-cli.zip;     unzip sonar-scanner-cli.zip;     rm sonar-scanner-cli.zip sonar-scanner-cli.zip.asc;     mv sonar-scanner-${SONAR_SCANNER_VERSION} ${SONAR_SCANNER_HOME};     pip install --no-cache-dir --upgrade pip;     pip install --no-cache-dir pylint;     apk del --purge build-dependencies;     mkdir -p "${SRC_PATH}" "${SONAR_USER_HOME}" "${SONAR_USER_HOME}/cache";     chown -R scanner-cli:scanner-cli "${SONAR_SCANNER_HOME}" "${SRC_PATH}";     chmod -R 777 "${SRC_PATH}" "${SONAR_USER_HOME}";]: exit code: 1

```

**Comment by pierre-guillot-gh** [comment]
Ok I was trying to build with the wrong alpine base image. building with alpine 3.17 works fine. I'm testing the image now 👀

**Comment by pierre-guillot-gh** [comment]
The image is working well on my side.

**Review by carminevassallo — APPROVED** [review]
The resulting container works well on my side as well, thanks!

**Pull request merged**
