### PR TITLE
Bump alpine from 3.14 to 3.15

### PR DESCRIPTION
**Pull request by candrews**
It's nice to use the latest versions of base images for security, bug fixes, etc

Here's the Alpine 3.15 release announcement: https://alpinelinux.org/posts/Alpine-3.15.0-released.html

### CODE REVIEW

**Comment by tobias-trabelsi-sonarsource** [comment]
Anything in particular why you want to use alpine 3.15? yeah it's released but 3.14 is still supported for the time being. What would be the benefit here?

also can you make sure to adapt the [rebuild logic](https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/.github/workflows/rebuild.yml) here as well?

**Comment by candrews** [comment]
> also can you make sure to adapt the [rebuild logic](https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/.github/workflows/rebuild.yml) here as well?

I've done so and updated this PR accordingly.

**Comment by candrews** [comment]
> Anything in particular why you want to use alpine 3.15?

Not in particular - just later versions (which tends to mean better security, support, and features). I find it to be a best practice to use the latest supported versions of dependencies.

> yeah it's released but 3.14 is still supported for the time being.

For the time being, yes. Plus one always gets better support with later versions.

> What would be the benefit here?

Let me turn that around - what's the benefit of sticking to the old version?

**Comment by tobias-trabelsi-sonarsource** [comment]
>For the time being, yes. Plus one always gets better support with later versions.

3.14 is supported until 2023-05-01
3.15 is supported until 2023-11-01
We are talking about 6 month more in over a year from now 

>Let me turn that around - what's the benefit of sticking to the old version?

stability, known dependencies and a system known to the user base... 

i get where you are coming from but as we as a company need to take a lot more components into consideration and i am not really sold yet. If there is really something in alpine 3.15 that would make a difference i am all for it to move to 3.15 but for now i'd like to keep the base image consistent with the one that is used in the SonarQube images as well. 

A lot of the improvements in 3.15 are targeting bare metal systems or desktop environments. We can not update java yet as stated in the previous PR so this is also not relevant here. 4096 bit RSA signatures for packages are nice but not a real world benefit yet.

that all said, i will close this PR now and revisit it when we move the scanners to java 17 and probably update the SQ base image as well in the same step. Thanks for the contribution and stating your points

**Pull request closed without merging**
