### PR TITLE
SCANDOCKER-3 Update release pipeline to support new versioning

### PR DESCRIPTION
**Pull request by csaba-feher-sonarsource**
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).

With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [x] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [x] If there is a [JIRA](http://jira.sonarsource.com/browse/SQSCANNER) ticket available, please make your commits and pull request start with the ticket ID (SQSCANNER-XXXX)

We will try to give you feedback on your contribution as quickly as possible.

Thank You!
The SonarSource Team

### CODE REVIEW

**Comment by csaba-feher-sonarsource** [comment]
I have tested building a dummy release pipeline. 
- The push part was not tested
- Also, this line, whether it gets the right value from the tag name, was not tested. I did not have a tag for that . `full_image_tag=${{GitHub.event.release.tag_name }}`

**Review by henryju — APPROVED** [review]
LGTM, we will test a release on Monday

**Comment by robross0606** [comment]
I'm confused by these changes.  If this project is going to deviate from Sonar's regular versions, where and how do we log issues referencing the image version?

**Comment by henryju** [comment]
As for all Sonar products, our community entry point (for reporting issues, asking for help or feature requests) is our [community forum](https://community.sonarsource.com/). Then we will create appropriate issues in [JIRA](https://sonarsource.atlassian.net/browse/SCANDOCKER) accordingly.

**Pull request merged**
