### PR TITLE
upgrade sonar cli and node

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David Karlsen <david@davidkarlsen.com>

---
This change is [Reviewable](https://reviewable.io/reviews/sonarsource/sonar-scanner-cli-docker/42)

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@amelie-renard-sonarsource ptal?

**Comment by pierre-guillot-sonarsource** [comment]
Hello, thanks for your contribution. I opened a separated PR for upgrading sonar-scanner-cli, and a jira ticket on our side to automate the release of the docker image at the same time as the downloadable zip.

About node, any specific reason for suggesting this upgrade ?

**Comment by davidkarlsen** [comment]
@pierre-guillot-sonarsource I just think it sane to run on latest patch-level - even upgrade to 12 could make sense due to release-cycles and exec speed.

**Comment by davidkarlsen** [comment]
https://levelup.gitconnected.com/whats-new-in-node-12-e00111ffb83f (speed, tls1.3, etc)

**Pull request merged**
