### PR TITLE
openssh included

### PR DESCRIPTION
**Pull request by vinodjoy**
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).

With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] If there is a [JIRA](http://jira.sonarsource.com/browse/SQSCANNER) ticket available, please make your commits and pull request start with the ticket ID (SQSCANNER-XXXX)

We will try to give you feedback on your contribution as quickly as possible.

Thank You!
The SonarSource Team

### CODE REVIEW

**Comment by klaudio-sinani-sonarsource** [comment]
Hello @vinodjoy! Thank you very much for taking the time to contribute to the repository!

Would you mind providing more context behind your change as well as why you need to include `openssh` in the image?

Thank you in advance for your help!

**Comment by jacek-poreda-sonarsource** [comment]
@vinodjoy Are you still interested in pushing for this change? Could you explain the reasoning for it as my colleague asked? If not we will close this PR within the upcoming days.

**Comment by vinodjoy** [comment]
Sorry for the delay. I just wanted to have ssh supported in the image which can help in cloning git repos using ssh.

**Comment by leo-geoffroy-sonarsource** [comment]
Hello @vinodjoy 
It is not clear why you want to add the openssh dependency to this docker image.
What could help is to provide an example of what you want to achieve and why it is not possible with the current image.
I will close this PR, feel free to give more information as suggested above if this change still makes sense.

**Pull request closed without merging**
