### PR TITLE
Bumped SonarScaner CLI to version 4.5.0.2216

### PR DESCRIPTION
**Pull request by mark-rekveld-sonarsource**
Bumped the version of the CLI in the docker file.

This bump was not covered in the automated release. Should we attempt to do this?
Use a simple method to update the version in the Dockerfile and commit it from the release flow.

### CODE REVIEW

**Comment by malena-ebert-sonarsource** [comment]
Why do we set a fixed version?

I would prefer setting the environment variable `SONAR_SCANNER_VERSION` during building. The build argument `SONAR_SCANNER_VERSION` holds the needed value. 

I think it is not possible to have the same name for the environment variable and the build argument.

**Comment by mark-rekveld-sonarsource** [comment]
> I would prefer setting the environment variable SONAR_SCANNER_VERSION during building dynamically.

Sounds like a good idea. Would the value be picked from the latest tag/release created?

**Comment by malena-ebert-sonarsource** [comment]
The value is populated from the `get_version` step of the release pipeline: `docker build ... --build-arg SONAR_SCANNER_VERSION=${{ steps.get_version.outputs.cli_version }}`

**Comment by mark-rekveld-sonarsource** [comment]
> The value is populated from the get_version step of the release pipeline

Can the nightly pipeline access the variables in the release pipeline? Or should the release pipeline update the env var in the repo after a run?

**Comment by malena-ebert-sonarsource** [comment]
No, both pipelines are independent.
The latest release version needs to be stored somewhere.

* One approach would be to use the latest git tag with the full version. (An additional tag would be nessesary).
* The other approach would be to store the version in a file of the repository.
  * In the Dockerfile
  * In an additional file

**Comment by mark-rekveld-sonarsource** [comment]
Maybe updating the Docker file would be a nice solution. This would also allow devs to build the image locally without the need to provide the build argument explicitly

**Comment by CCFenner** [comment]
The tag `sonarsource/sonar-scanner-cli:4.5` is already out but shipping `v4.4`. That is a bit confusing.

**Comment by mark-rekveld-sonarsource** [comment]
> The tag sonarsource/sonar-scanner-cli:4.5 is already out but shipping v4.4. That is a bit confusing.

The docker build uses a build argument to determine the version of the SonarScanner CLI, this version is currently defaulted to 4.4 but 4.5 is available on the Docker Hub.

**Comment by mark-rekveld-sonarsource** [comment]
> It is a bit confusing that `sonarsource/sonar-scanner-cli:4.5` is now available without containing `v4.5` of the sonar-scanner-cli.
> 
> ```
> docker run -it --rm sonarsource/sonar-scanner-cli:4.5 -v   
> INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
> INFO: Project root configuration file: NONE
> INFO: SonarScanner 4.4.0.2170
> INFO: Java 11.0.6 AdoptOpenJDK (64-bit)
> INFO: Linux 4.19.76-linuxkit amd64
> ```

Sorry about then, This PR will correct this and a new release will be pushed to Docker hub today

**Review by malena-ebert-sonarsource — APPROVED** [review]

**Pull request merged**
