### PR TITLE
fix: improve entrypoint

### PR DESCRIPTION
**Pull request by caarlos0**
this makes possible to pass arguments to the docker image and set the projectBaseDir by default.

### CODE REVIEW

**Comment by lenntt** [comment]
I built the image and can confirm this works as I'd would expect.
Merging this in, requires updating the documentation.

For further illustration, the following command works for me:
```
docker run -u 0:0 -v $PWD:/usr/src sonar-scanner-cli '-Dsonar.login=****' '-Dsonar.host.url=********' '-Dproject.settings=/usr/src/ci/sonar/sonar-project.properties'
```

**Comment by bstoccoGenesys** [comment]
I am looking for this change as well

**Comment by kav** [comment]
Also worth calling out; this approach allows you to use any of the standard methods (i.e. files) rather than forcing you to use the envars

**Comment by jtraulle** [comment]
Is there anything blocking here that prevent the merge of the PR ?

**Comment by eaardal** [comment]
Also waiting for this 🤞

**Comment by michal-duda-sonarsource** [comment]
With just released version 4.4 you can pass all analysis parameters like you would pass them to sonar-scanner:
docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=${SONAR_PROJECT_KEY}

**Pull request closed without merging**
